### ISSUE TITLE
for Monterey

### ISSUE THREAD

**Issue by rich1111** [AskDavis/LG-Gram-17Z90N#16]
Hi, here EFI seem for Monterey, 
https://www.olarila.com/topic/28434-hackintosh-efi-opencore-lg-gram-17z90n-v-icelake/#comment-173390

but WIFI not working, can someone fix it?

**Comment by rich1111** [comment]
Hi, anyone successfully install Monterey with above? I stuck at Monterrey installation screen after booting from EFI, not trying upgrade from Big Sur.

**Comment by rich1111** [comment]
I upgrade from Big Sur to Monterey using this EFI succesfully.

**Comment by thaiiy** [comment]
Thanks for your link. 

I managed to combine your linked EFI with the one from @1OldSWguy to get the following EFI (attached, spread over three threads due to size limit).

Now I have upgraded to Monterey with the following remaining issues, which each ACPI version fixes but I can't get it all working.

With the ACPI containing DSDT.aml only:
- brightness keys work
- clamshell mode works - internal display disabled and your desktop is moved to your external monitor
- SLEEP WAKE failure

With ACPI containing SSDTs:
- brightness keys DO NOT work - but strangely work on external Mac keyboard
- clamshell mode DOES NOT work - internal display goes off but is still online, so desktop is not transferred to external monitor. You can still see the internal display in System Preferences, Display arrangements.
- Sleep Wake is WORKING

On either ACPI, almost everything else appears to work: Bluetooth, WiFi, FaceTime, display brightness (software controlled), audio, microphone.

USB ports might need fixing as left-side USB-A port isn't working.

I think the answer is all there but it requires a better brain than mine to solve it. I would appreciate your input.


[LG Gram 17 Monterey.zip](https://github.com/AskDavis/LG-Gram-17Z90N/files/9539592/LG.Gram.17.Monterey.zip)

**Comment by thaiiy** [comment]
First part of kexts folder

[Kexts 1.zip](https://github.com/AskDavis/LG-Gram-17Z90N/files/9539600/Kexts.1.zip)

**Comment by thaiiy** [comment]
Second part of kexts folder

USB Map updated - Left USB-A port now working.

[USBMapLG17.kext.zip](https://github.com/AskDavis/LG-Gram-17Z90N/files/9539664/USBMapLG17.kext.zip)
[Uploading Kexts 2.zip…]()

**Comment by dandantsui** [comment]
Thanks for posting this! I will try this when I have the chance.

> * brightness keys DO NOT work - but strangely they work on external Mac keyboard with dedicated keys (F1/F2).

This may be fixed with finding the problematic SSDT that has remapped the keyboard function keys.

**Comment by daniyo27** [comment]
Thanks for posting this! I will try this when I have the chance.

> brightness keys DO NOT work - but strangely they work on external Mac keyboard with dedicated keys (F1/F2).

This may be fixed with finding the problematic SSDT that has remapped the keyboard function keys. Alternatively, you could just go to Keyboard Shortcuts and remap the Brightness keys in System Preferences.

**Comment by thaiiy** [comment]
@daniyo27 Wow, never thought I could remap brightness keys through System Preferences, but it works! F2/3 mapped to Brightness controls now. So things are just about perfect now...

**Comment by 1OldSWguy** [comment]
The brightness keys (Fn+F2; Fn+F3) functions on our Gram model can be mapped via SSDT-FNKey. The Olarila patched DSDT also maps the same. They work perfectly on my Hack with the SSDT-FNKey, but I don't think this repository has been updated with this SSDT so maybe that's causing the issue.

As for HDMI out, Apple removed HDMI display out support from the ICL graphics driver. It is doubtful that any hacOS developer will create a solution for this unsupported functionality, but we all can cheer them on :)

**Comment by thaiiy** [comment]
I see, well thanks for saving me countless hours trying out all the framebuffers and BusIDs! 

Can you please share the SSDT-FNkey you made? 

Also, your config.plist - I am having trouble with USB-C to HDMI with a Dell WD15 dock. Display out works fine but when I unplug the cable, it give a kernel panic and reboots with the following displayed on restarting:


panic(cpu 0 caller 0xffffff7fa284eca1): "[IGFB][PANIC][POWER    ] " "Cannot enable DC6 without PSR or doze/sleep srd control: 0x00100001 PG state: 0x00000003 fuse status: 0x8c000000\n" @AppleIntelController.cpp:5594

It doesn't seem to happen with another USB-C dock (HP) though.

This is my current boot-arg:

boot-args	-v igfxonln=1 -igfxblr -noDC9 igfxfw=2 -igfxdbeo uia_exclude=USR1;USR2 -nodisplaysleepDC6

**Comment by 1OldSWguy** [comment]
I replaced -nodisplaysleepDC6 with dc6config=0 and the kernel panic reboot from unplug of USB-C to HDMI external display cable was fixed. I also use -igfxcdc so you may need it as well (or the equivalent in DeviceProperties) I didn't try all combinations of sleep/wake so you may want to confirm with your testing.

I have attached the FNKey SSDT and the LGGramAssistant App that goes with it. To use this SSDT you also need the _Qnn to XQnn ACPI patch renames that are in my config.plist (_Q01 -> XQ01; _Q34 -> XQ34; _Q36 -> XQ36; _Q37 -> XQ37; _Q50 -> XQ50; _Q51 -> XQ51; _Q72 -> XQ72; _QFF -> XQFF). You also need the LGGramAssistant App installed and running to get the WiFi, Bluetooth, and NightShift hot keys functions. I added LGGramAssistant to my startup items as its menu item's builtin method doesn't work.
[SSDT-FNKey_aml.zip](https://github.com/AskDavis/LG-Gram-17Z90N/files/9579700/SSDT-FNKey_aml.zip)
[LGGramAssistantAPP.zip](https://github.com/AskDavis/LG-Gram-17Z90N/files/9579710/LGGramAssistantAPP.zip)

**Comment by thaiiy** [comment]
Funny that the kernel panics have stopped by themselves... maybe I got the framebuffers and device_id wrong and it is working on reversion to 0200518A and 528A0000 - not sure why the Device ID is different to the framebuffer but it is working! I'll keep your other boot-args in mind if the panics recur.

Could you please post your config.plist because I can't see the ACPI patches in your EFI on the other Lid Disable thread?

Thanks so much.

**Comment by 1OldSWguy** [comment]
Here is the PLIST config entries required to use the SSDT-FNKey enabler.
[config_FNKey_plist.zip](https://github.com/AskDavis/LG-Gram-17Z90N/files/9586672/config_FNKey_plist.zip)

**Comment by daniyo27** [comment]
@thaiiy I tried your EFI and there were a lot of things to fix, so I readapted yours and updated to OC 0.8.5

The only issue now is that the display doesn't wake when waking from sleep but the external displays via USB-C do work.

I've attached my EFI here -- also for those who have trouble from the previous attached EFI.
[https://mega.nz/file/wewlXIxT#_okA9wo89dtvLjmVDlFCOOTujQgrwP1_TfKd--RxQ5o](https://mega.nz/file/wewlXIxT#_okA9wo89dtvLjmVDlFCOOTujQgrwP1_TfKd--RxQ5o)

**Comment by AskDavis** [comment]
updated Opencore and added brightness keys, (Thanks 1OldSWguy and daniyo27)
